export type EventsPage = {
  heroEyebrow: string;
  heroHeadline: string;
  heroHeadlineAccent: string;
  heroSubheading: string;
  eventFeaturedHeadline: string;
  registerEyebrow: string;
  registerCloseLabel: string;
  registerFullNameLabel: string;
  registerFullNameError: string;
  registerEmailLabel: string;
  registerEmailRequiredError: string;
  registerEmailInvalidError: string;
  registerSubmitLabel: string;
  confirmHeadline: string;
  confirmBodyBeforeName: string;
  confirmBodyBeforeEmail: string;
  confirmBodyAfterEmail: string;
  confirmCloseLabel: string;
};
